name: build and push
on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build frontend
        working-directory: ./frontend
        run: docker build -t goal-reminder-frontend:test .
        
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build backend
        working-directory: ./backend
        run: docker build -t goal-reminder-backend:test .